services:
  db:
    image: mysql:latest
    container_name: mysql_db
    hostname: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo # Replace with a strong password
      MYSQL_DATABASE: demo      # Optional: Create a default database
      MYSQL_USER: demo          # Optional: Create a default user
      MYSQL_PASSWORD: demo      # Optional: Set password for the default user
    ports:
      - "3307:3306" # Maps container port 3306 to host port 3306
    volumes:
      - mysql_data:/var/lib/mysql # Persist data in a named volume
volumes:
  mysql_data: